Update README to start a new session
thephpleague/oauth2-github pull request #15
Opened 2018-11-08 04:20 UTC by Mataniko

The sample in the README fails because there's no session available and the state is never saved. 

Initializing a session fixes this and turns the snippet into a working sample.

2019-05-28 20:18 UTC, DanielRuf commented
Bump. Still relevant.

2019-05-28 20:21 UTC, DanielRuf requested changes

2019-05-28 20:21 UTC, DanielRuf commented on README.md
> +if ( ! session_id() ) @ session_start();
Why not

```
if ( ! session_id() ) {
    session_start();
}
```

2021-10-21 15:53 UTC, closed without merging

2021-10-21 15:53 UTC, shadowhand commented
This PR is stale and had to be closed. Please recreate if still relevant.