Add a workaround retrieving the resource owner email
thephpleague/oauth2-github pull request #20
Opened 2022-11-03 09:20 UTC by Gyvastis

The resource owner email is always `null`, as stated in the issue https://github.com/thephpleague/oauth2-github/issues/19.

2022-11-03 13:31 UTC, shadowhand requested changes
This needs testing.

2022-11-03 13:31 UTC, shadowhand commented on src/Provider/Github.php
> +        if (($response['email'] ?? null) == null) {
```suggestion
        if (! ($response['email'] ?? null)) {
```

2022-11-03 13:31 UTC, shadowhand commented on src/Provider/Github.php
> +            if (false === is_array($responseEmail)) {
```suggestion
            if (! is_array($responseEmail)) {
```

2022-11-03 13:31 UTC, shadowhand commented on src/Provider/Github.php
> +                throw new \UnexpectedValueException(
This should be imported with a `use` statement.

2022-11-03 13:31 UTC, shadowhand commented on src/Provider/Github.php
> +            $response['email'] = $responseEmail[0]['email'];
Is there guaranteed to be at least one email?

2022-11-03 13:31 UTC, shadowhand commented on src/Provider/Github.php
> +            $response['email'] = $responseEmail[0]['email'];
```suggestion
            $response['email'] = $responseEmail[0]['email'] ?? null;
```

I don't think there is a need for the type check at all. If the request fails then there will already be an error.

2022-11-03 13:32 UTC, shadowhand commented on src/Provider/Github.php
> +        if (($response['email'] ?? null) == null) {
Actually this can't be used, because we support PHP 7.3+ with this package.
```suggestion
        if (empty($response['email'])) {
```

2022-11-03 13:36 UTC, shadowhand requested changes

2022-11-03 13:36 UTC, shadowhand commented on src/Provider/Github.php
> +        if (! ($response['email'] ?? null)) {
See my comment about PHP 7.3+ support.

2022-11-03 13:36 UTC, shadowhand commented on src/Provider/Github.php
> +            $response['email'] = $responseEmail[0]['email'] ?? null;
And here too.

2022-11-03 15:28 UTC, shadowhand approved these changes

2022-11-03 15:29 UTC, shadowhand commented
@Gyvastis this looks great. Once tests are added I will merge.

2022-11-04 13:43 UTC, Gyvastis commented
> @Gyvastis this looks great. Once tests are added I will merge.

Done

2022-11-04 13:58 UTC, shadowhand approved these changes
Thank you! Looks great.

2022-11-04 13:58 UTC, merged

2022-11-04 14:03 UTC, shadowhand commented
Released as version 3.1.0.